FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore     src/Events/Events.Presentation/Events.Presentation.csproj

RUN dotnet publish     src/Events/Events.Presentation/Events.Presentation.csproj     -c Release     -o /app/publish     --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Events.Presentation.dll"]
